spring.datasource.url=jdbc:${MYSQL_URL:mysql://localhost:3306/bikeRentalAndRideSharing}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}