spring.application.name=bikeRentalAndRideSharing

spring.datasource.url=jdbc:mysql://localhost:3306/bikeRentalAndRideSharing
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=